### PR TITLE
PipeConfigChunks(): don't crash on incomplete chunks

### PR DESCRIPTION
**Pull request by Al2Klimov**

### CODE REVIEW

**Comment by Al2Klimov** [comment]
## Scenario

1. Dump a large config
2. Clear conf.d
3. Reload

## Before

panic: runtime error: slice bounds out of range [:197] with capacity 1

## After

**Comment by julianbrost** [comment]
The idea when I wrote this code was that all slices have the same length or are nil. I'd prefer to check where the lengths diverge rather than fix it this way. I can also take a look at this.

Also fixes #263 I created today (noticed the same today).

**Comment by Al2Klimov** [comment]
Yes, please have a look!

**Comment by N-o-X** [comment]
This PR isn't needed anymore after our RC2 rework.

**Pull request closed without merging**
