### PR TITLE
NewRDBWrapper(): let our Redis client re-try for us

### LINKED ISSUE #164: IcingaDB fails with: 127.0.0.1:6380: i/o timeout
I played around with huge environments (e.g. 20.000 Hosts/200.000 Services) and IcingaDB fails with:

```
Apr 23 10:26:45 idb3.localdomain icingadb[15916]: time="2020-04-23T10:26:45+02:00" level=info msg="Added 2 state history entries in the last 20 seconds"
Apr 23 10:26:56 idb3.localdomain icingadb[15916]: time="2020-04-23T10:26:56+02:00" level=info msg="Icinga 2 sent no heartbeat for 15 seconds. Pausing sync" UUID=038b40c4-2860-41e3-8c6d-05c186d37b07 context=HA environment=da39a3ee5e6b4b0d3255bfef95601890afd80709
Apr 23 10:26:58 idb3.localdomain icingadb[15916]: time="2020-04-23T10:26:58+02:00" level=info msg="Icinga 2 sent heartbeat. Starting sync" UUID=038b40c4-2860-41e3-8c6d-05c186d37b07 context=HA environment=da39a3ee5e6b4b0d3255bfef95601890afd80709
Apr 23 10:27:05 idb3.localdomain icingadb[15916]: time="2020-04-23T10:27:05+02:00" level=info msg="Added 3 state history entries in the last 20 seconds"
Apr 23 10:27:13 idb3.localdomain icingadb[15916]: time="2020-04-23T10:27:13+02:00" level=info msg="Icinga 2 sent no heartbeat for 15 seconds. Pausing sync" UUID=038b40c4-2860-41e3-8c6d-05c186d37b07 context=HA environment=da39a3ee5e6b4b0d3255bfef95601890afd80709
Apr 23 10:27:25 idb3.localdomain icingadb[15916]: time="2020-04-23T10:27:25+02:00" level=info msg="Added 2 state history entries in the last 20 seconds"
Apr 23 10:27:29 idb3.localdomain icingadb[15916]: time="2020-04-23T10:27:29+02:00" level=info msg="Icinga 2 sent heartbeat. Starting sync" UUID=038b40c4-2860-41e3-8c6d-05c186d37b07 context=HA environment=da39a3ee5e6b4b0d3255bfef95601890afd80709
Apr 23 10:27:45 idb3.localdomain icingadb[15916]: time="2020-04-23T10:27:45+02:00" level=info msg="Added 2 state history entries in the last 20 seconds"
Apr 23 10:27:45 idb3.localdomain icingadb[15916]: time="2020-04-23T10:27:45+02:00" level=info msg="Icinga 2 sent no heartbeat for 15 seconds. Pausing sync" UUID=038b40c4-2860-41e3-8c6d-05c186d37b07 context=HA environment=da39a3ee5e6b4b0d3255bfef95601890afd80709
Apr 23 10:28:01 idb3.localdomain icingadb[15916]: time="2020-04-23T10:28:01+02:00" level=fatal msg="read tcp 127.0.0.1:47914->127.0.0.1:6380: i/o timeout"
Apr 23 10:28:01 idb3.localdomain systemd[1]: icingadb.service: Main process exited, code=exited, status=1/FAILURE
Apr 23 10:28:01 idb3.localdomain systemd[1]: icingadb.service: Failed with result 'exit-code'.
```

I don't think it's related to system resources. A restart of icingadb.service solves the problem.

**Versions:**
icinga2: v2.12.0-rc1
icingadb: v1.0.0-rc1
icingaweb2: v2.8.0-rc1
icingadb-web: v1.0.0-rc1

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #164

### CODE REVIEW

**Comment by Al2Klimov** [comment]
## The mentioned internals

```
retry	minBackoff	maxBackoff		backoff	return	Σ
						
1	5	60		10	0,136600670860562	0,136600670860562
2	5	60		20	13,2306633157067	13,3672639865673
3	5	60		40	22,5854212676125	35,9526852541798
4	5	60		60	37,1154700129991	73,068155267179
5	5	60		60	34,8175599321308	107,88571519931
6	5	60		60	47,2386654228106	155,12438062212
7	5	60		60	2,05784837807504	157,182229000195
8	5	60		60	10,7924165074782	167,974645507674
9	5	60		60	28,1290724208552	196,103717928529
10	5	60		60	44,4903958252939	240,594113753823
11	5	60		60	23,3291658143441	263,923279568167
12	5	60		60	29,7039296410265	293,627209209193
```

**Comment by Al2Klimov** [comment]
I've removed the old one:

https://github.com/Icinga/icingadb/pull/179/files#diff-c747d65e67206c9b4381d26ee1ab5f1fL221-R230

**Comment by N-o-X** [comment]
But we still have: https://github.com/Icinga/icingadb/blob/c5739e2deea9a0e1581759490c309904d06122b2/connection/redis.go#L187

and "ticker" for it:
https://github.com/Icinga/icingadb/blob/c5739e2deea9a0e1581759490c309904d06122b2/connection/redis.go#L160

And this ticker mechanism becomes useless with the new implementation, because we don't get any feedback from our Redis library until 5 minutes later. 

This also disables our "disconnected" logging. There are no log messages until 5 minutes after connection loss. I'm not sure if that problem is fixable with the library way of retrying.

**Comment by Al2Klimov** [comment]
# To do

* [ ] https://github.com/go-redis/redis/pull/1324
* [ ] Make use of it

**Comment by dasJ** [comment]
Since nobody at go-redis seems to care... maybe switch to your fork until it's merged?

**Pull request closed without merging**
