### PR TITLE
Unify notation of `n * time.Duration`

### PR DESCRIPTION
**Pull request by lippserd**
Merge after #698 because of https://github.com/Icinga/icingadb/pull/738#issuecomment-2049074001.

### CODE REVIEW

**Review by oxzi — COMMENTED** [review]
The changes are looking fine. However, I found one other occurrence with `egrep -r 'time\..*[0-9]+' .`:
https://github.com/Icinga/icingadb/blob/8ef32e1a63183044f49ae5bbd8d1e2a87d93a050/pkg/icingadb/driver.go#L58

**Comment by lippserd** [comment]
> The changes are looking fine. However, I found one other occurrence with `egrep -r 'time\..*[0-9]+' .`:
> 
> https://github.com/Icinga/icingadb/blob/8ef32e1a63183044f49ae5bbd8d1e2a87d93a050/pkg/icingadb/driver.go#L58

Yes, but #698 changes that line anyway.

**Comment by oxzi** [comment]
As #698 got merged, this can be rebased and also merged before the release.

**Review by oxzi — APPROVED** [review]
LGTM.

I haven't found any other occurrences in the code base, either with my prior grep nor with a more specific `egrep -r 'time\.[A-Za-z]+[\* ]+[0-9]+' .`.

**Review by yhabteab — APPROVED** [review]

**Review by julianbrost — APPROVED** [review]

**Pull request merged**
