### PR TITLE
GHA: go mod tidy

### PR DESCRIPTION
**Pull request by Al2Klimov**
If this changes go.*, complain about the non-perfect file(s).

### CODE REVIEW

**Comment by lippserd** [comment]
Please add a description.

**Comment by lippserd** [comment]
If I'm not mistaken, dependabot automatically runs `go mod tidy`. So is that really necessary?

**Comment by Al2Klimov** [comment]
Actually I'm not sure. But if **I'm** not mistaken, dependabot isn’t our only contributor.

**Comment by lippserd** [comment]
> But if **I'm** not mistaken, dependabot isn’t our only contributor.

Sure, but dependabot will fix any _mistakes_. So I'd be ok if this isn't perfect until a dependabot PR fixes it. Because why bother a contributor when it will be fixed automatically anyway.

**Comment by Al2Klimov** [comment]
We already bother them w/ fmt, lint and even vet. The go.sum cryptographically secures that we have no surprises. I'd like it to be always-perfect and not to wait for dependabot's mercy. If we can squash external commits, we can also run go mod tidy.

**Review by lippserd — APPROVED** [review]

**Pull request merged**
