### PR TITLE
Enlarge {comment,downtime}#name 255 -> 548

### LINKED ISSUE #273: Comment and downtime name columns too small
Adding a comment or downtime for a host/service with a long name will crash Icinga DB because the value doesn't fit into the column.

Host and service names have currently a limit of 255 chars.

* For host comments/downtimes, the respective name column needs to be that big plus the id length
* For service comments/downtimes, the respective name column has to be 255*2 chars long plus the id length

### PR DESCRIPTION
**Pull request by Al2Klimov**
I.e. large enough for "host.name!service.name!UUID".

fixes #273

### CODE REVIEW

**Review by lippserd — COMMENTED** [review]
For services this should be `255+1+255+1+36` or am I missing something?

**Comment by Al2Klimov** [comment]
`service#name` is 255 large.

**Comment by nilmerg** [comment]
But it's `host#name!service#name` for service downtimes and comments, isn't it?

**Comment by Al2Klimov** [comment]
I’m afraid... yes.

https://github.com/Icinga/icinga2/blob/5af40fa5330460ef519bf8a79d4f49f5d11dc66b/lib/icingadb/icingadb-objects.cpp#L1253-L1258

🤦‍♂️ 🐘

**Review by lippserd — CHANGES_REQUESTED** [review]
Please use host_name and service_name in the comment.

**Comment by Al2Klimov** [comment]
I kept it consistent with the other comments.

**Comment by lippserd** [comment]
> I kept it consistent with the other comments.

I see. Then it should be host.name and service.name. Sry!

**Review by lippserd — APPROVED** [review]

**Pull request merged**
