### PR TITLE
Icinga DB: introduce Checkable#last_comment_id

### LINKED ISSUE #317: Column `last_comment_id` for hosts and services
Web would like to show the latest comment (no matter if ack or not) in the list. For this we need the `last_comment_id` in the `host` and `service` tables.

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #317
refs Icinga/icinga2#8916

### CODE REVIEW

**Comment by Al2Klimov** [comment]
## Test

Initial:

```
+----------------------+
| HEX(last_comment_id) |
+----------------------+
| NULL                 |
+----------------------+
```

First:

```
+------------------------------------------+
| HEX(last_comment_id)                     |
+------------------------------------------+
| A6FEFCF8BA023A2370DB0730A4D8C2D5AC590599 |
+------------------------------------------+
```

Second:

```
+------------------------------------------+
| HEX(last_comment_id)                     |
+------------------------------------------+
| A70C60F401A3C7D86B0A1AE69F77A8B7559D011E |
+------------------------------------------+
```

Third:

```
+------------------------------------------+
| HEX(last_comment_id)                     |
+------------------------------------------+
| 5E200D1D42FCE301681325DB31D6095332413E52 |
+------------------------------------------+
```

Removed third:

```
+------------------------------------------+
| HEX(last_comment_id)                     |
+------------------------------------------+
| A70C60F401A3C7D86B0A1AE69F77A8B7559D011E |
+------------------------------------------+
```

**Comment by Al2Klimov** [comment]
@lippserd Any idea why Icinga DB doesn’t take the actually updated stream into account?

**Comment by Al2Klimov** [comment]
The current Icinga/icinga2#8916 implementation purrs like a cat. But Icinga DB doesn’t update MySQL.

**Comment by lippserd** [comment]
Blocked by #325

**Comment by Al2Klimov** [comment]
For better visualization whether we can proceed:

## Blocked by

* #325

**Review by julianbrost — APPROVED** [review]

**Pull request merged**
