### PR TITLE
Delete config.yml.example

### PR DESCRIPTION
**Pull request by Al2Klimov**

### CODE REVIEW

**Review by lippserd — APPROVED** [review]

**Review by julianbrost — CHANGES_REQUESTED** [review]
Why?

**Comment by Al2Klimov** [comment]
https://github.com/Icinga/icingadb/pull/366#discussion_r717414385

**Comment by julianbrost** [comment]
That comment gives no reasoning at all.

**Comment by lippserd** [comment]
> That comment gives no reasoning at all.

That file was only used for packaging but we (should) no longer depend on it. (Same for the systemd service file.)

**Comment by julianbrost** [comment]
The systemd service file got removed in #345 and unfortunately, that PR doesn't provide any reasoning either. I can't remember the reason and can't reconstruct it either. One thing I could have imagined that the service file differs between distributions but not even that's the case right now.

Anyways, I think the example config in the source repo is quite helpful to get people started working on the code. To get Icinga DB running, you need a config file (you can do without a systemd service file, that's why it's valid to make a difference between the two in my opinion), so it's handy to be able to just copy it over.

**Comment by lippserd** [comment]
Let's keep it.

**Pull request closed without merging**
