### PR TITLE
Use github.com/intel-go/fastjson

### PR DESCRIPTION
**Pull request by Al2Klimov**

### CODE REVIEW

**Comment by Al2Klimov** [comment]
May be an alternative to #46.

**Comment by lippserd** [comment]
Do we have a performance improvement here?

**Comment by Al2Klimov** [comment]
According to their docs and our code – yes.

**Comment by lippserd** [comment]
Please provide a benchmark here.

**Comment by N-o-X** [comment]
And please don't work on this before 1.0-rc1.

**Comment by Al2Klimov** [comment]
According to this hijack:

```go
package hijack

import (
	"github.com/intel-go/fastjson"
	"github.com/prometheus/client_golang/prometheus"
	"time"
)

var uspb = prometheus.NewSummary(prometheus.SummaryOpts{Name: "uspb"})
var _ = func() struct{} {
	prometheus.Register(uspb)
	return struct{}{}
}()

func Unmarshal(data []byte, v interface{}) error {
	defer func(start time.Time) {
		uspb.Observe(float64(time.Now().Sub(start)) / float64(time.Microsecond) / float64(len(data)))
	}(time.Now())
	return fastjson.Unmarshal(data, v)
}
```

... fastjson doubles the speed.

**Comment by lippserd** [comment]
`intel-go/fastjson` has been archived. I would not count on that anymore.

**Pull request closed without merging**
