### PR TITLE
Treat SQL serialization failures as connection errors

### LINKED ISSUE #170: IcingaDB fails with: "Error 1205: Lock wait timeout exceeded"
I played around with huge environments (e.g. 25.000 Hosts/250.000 Services) and IcingaDB fails with:

```
Apr 29 08:07:48 idb3.localdomain icingadb[22708]: time="2020-04-29T08:04:25+02:00" level=debug msg="Syncing overdue indicators to database" amount=1000 overdue=false type=service
Apr 29 08:07:48 idb3.localdomain icingadb[22708]: time="2020-04-29T08:04:25+02:00" level=fatal msg="Error 1205: Lock wait timeout exceeded; try restarting transaction"
Apr 29 08:07:48 idb3.localdomain icingadb[22708]: time="2020-04-29T08:05:15+02:00" level=debug msg="service_customvar: Insert preparation worker started"
Apr 29 08:07:48 idb3.localdomain systemd[1]: icingadb.service: Main process exited, code=exited, status=1/FAILURE
Apr 29 08:07:48 idb3.localdomain systemd[1]: icingadb.service: Failed with result 'exit-code'.
```

**Versions:**
icinga2: v2.12.0-rc1
icingadb: 1.0.0+rc1.21
icingadb-redis: 1.0.0+rc1.21
icingaweb2: v2.8.0-rc1
icingadb-web: v1.0.0-rc1

### PR DESCRIPTION
**Pull request by Al2Klimov**
... to recover from them.

fixes #170

### CODE REVIEW

**Comment by Al2Klimov** [comment]
https://git.icinga.com/packaging/rpm-icingadb/pipelines/9414

**Comment by Al2Klimov** [comment]
https://git.icinga.com/packaging/deb-icingadb/pipelines/9415

**Comment by Al2Klimov** [comment]
To test, pick your distro from the build column and download the artifacts.

**Comment by N-o-X** [comment]
This PR isn't needed anymore after our RC2 rework.

**Pull request closed without merging**
