### PR TITLE
Update authors and remove authors whose code is no longer in the repo

### PR DESCRIPTION
**Pull request by lippserd**
- [ ] Decide how to keep this file up to date automatically, e.g. https://github.com/Icinga/icingadb/pull/313#issuecomment-892981183

### CODE REVIEW

**Comment by julianbrost** [comment]
Any plans for how we'll keep this file up-to-date in the long run? Like if we do it like in the icinga2 repo (i.e. automatically populate from Git authors), these people would show up again.

**Comment by lippserd** [comment]
With something like that:

`git ls-tree --name-only -r -z HEAD | xargs -0 -n1 git blame --line-porcelain | grep -ae "^author " -A1`

**Comment by Al2Klimov** [comment]
Are they such a burden for us? I'd just enable Probot and let it do its thing.

**Comment by lippserd** [comment]
> Are they such a burden for us? I'd just enable Probot and let it do its thing.

We have rewritten the whole thing 100%. So it is a lie to claim them as authors.

**Comment by lippserd** [comment]
Can we configure the probot to do its thing after a certain commit?

**Comment by Al2Klimov** [comment]
I could implement it. (But I'd consult colleague Drescher first (just to be sure).)

**Comment by julianbrost** [comment]
I think we should update the AUTHORS file in some form for RC2, even if it's not yet automated. Not sure about the mailmap though, I mean the commits are still somewhere in the history of this repo, so I wouldn't remove stuff from that file.

**Review by htriem — APPROVED** [review]
I really should switch to my icinga.com-Mail, but this is looking good for now.

**Pull request merged**
