### PR TITLE
Add CommandArgument#Separator

### PR DESCRIPTION
**Pull request by Al2Klimov**
## Blocked by

(not really)

* [ ] Icinga/icinga2#7919

### CODE REVIEW

**Review by julianbrost — CHANGES_REQUESTED** [review]
Misses the MySQL schema upgrade.

**Review by julianbrost — CHANGES_REQUESTED** [review]
`separator` is a [reserved word](https://dev.mysql.com/doc/refman/8.0/en/keywords.html#keywords-8-0-detailed-S) in MySQL. I'd just put it in <code>``</code> (rather than choosing a different name), that's already done in another place anyways (`notification_history.text`).

**Comment by julianbrost** [comment]
```
2022-05-17T08:32:32.133Z	FATAL	icingadb	Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'separator, description, argument_key_override, repeat_key, set_if, environment_i' at line 1
```

Do we have any special handling for the `text` column name? Or can you use `text` in a column list without quoting but for `separator`, you'd have to quote?

**Comment by Al2Klimov** [comment]
1. No.
2. Yes:

```
MariaDB [idb]> insert into lolcat(text) values(1);
ERROR 1146 (42S02): Table 'idb.lolcat' doesn't exist
MariaDB [idb]> insert into lolcat(separator) values(1);
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'separator) values(1)' at line 1
MariaDB [idb]>
```

"sep" ftw?

**Comment by Al2Klimov** [comment]
Or quoting ftw?

**Comment by lippserd** [comment]
> (how does it handle table names for PostgreSQL at the moment?)

We have a hack in order to quote it. Reserved words as column names are not a problem as we're always selecting fully qualified, i.e. `table_alias.column_name`.

**Comment by lippserd** [comment]
> We have a hack in order to quote it.

https://github.com/Icinga/icingadb-web/pull/508/commits/f251891f0f78b8c998e6880fb3cabda314d6d319

**Comment by julianbrost** [comment]
I have a slight preference towards `separator`, but only if it's possible with reasonable effort. So if nobody objects, I'd say try to add quoting, but get back to the discussion if this needs more complex changes than maybe writing some `JoinColumnNames` function to replace calls to `strings.Join(..., ", ")`.

**Review by lippserd — APPROVED** [review]

**Review by julianbrost — APPROVED** [review]

**Pull request merged**
