### PR TITLE
Schema consistency for relations

### PR DESCRIPTION
**Pull request by yhabteab**

### CODE REVIEW

**Comment by yhabteab** [comment]
### Blocked by

- https://github.com/Icinga/icinga2/pull/9384

**Comment by julianbrost** [comment]
For the overall picture: what's the motivation for this? I think I vaguely remember that there was something with how relations are handled in icingadb-web?

**Comment by nilmerg** [comment]
Yes, we lazy load some relations upon accessing specific properties on objects. (e.g. `$host->checkcommand`) Depending on whether the `checkcommand` column is selected in the query or not, the returned result differs.

**Review by julianbrost — CHANGES_REQUESTED** [review]
@nilmerg As you approved https://github.com/Icinga/icingadb-web/pull/546, can I just merge this PR once ready? (I don't expect more changes than to the schema upgrade.)

**Comment by nilmerg** [comment]
yes, go ahead

**Review by julianbrost — APPROVED** [review]

**Pull request merged**
