### PR TITLE
Schema: introduce downtime#creator

### LINKED ISSUE #231: Downtime tables should include downtime source/origin
Just faced again the issue that [Icinga 2 does not complain about a failed downtime removal](https://github.com/Icinga/icingaweb2/issues/4247) if it's coming from a scheduled downtime config object.

Icinga DB Web could hide the removal button in such a case, though there doesn't seem to be a column in the schema indicating what created the downtime. I'd like to have that included.

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #231

### CODE REVIEW

**Comment by Al2Klimov** [comment]
## Blocked by

* [ ] Icinga/icinga2#8631

**Comment by Al2Klimov** [comment]
```
➜  icingadb git:(feature/icingadb-scheduleddowntime-231) go run . -config my.ini
go: downloading github.com/google/uuid v1.2.0
INFO[0000] Connecting to Redis
INFO[0000] Connecting to MySQL
INFO[0000] Redis connection established
INFO[0000] SQL connection established
INFO[0000] Starting heartbeat listener
INFO[0000] Serving metrics at http://[0.0.0.0]:8080/metrics
INFO[0000] Got initial environment.                      UUID=d3764373-c753-491f-acea-161ffa2692f3 context=HA environment=da39a3ee5e6b4b0d3255bfef95601890afd80709
INFO[0000] Taking over.                                  UUID=d3764373-c753-491f-acea-161ffa2692f3 context=HA environment=da39a3ee5e6b4b0d3255bfef95601890afd80709
INFO[0001] Inserted 2 downtimes in 10.153787ms           action=insert benchmark=10.153787ms count=2 type=downtime
INFO[0001] Inserted 9 checkcommands in 11.701334ms       action=insert benchmark=11.701334ms count=9 type=checkcommand
INFO[0001] Inserted 7 checkcommand_customvars in 7.287776ms  action=insert benchmark=7.287776ms count=7 type=checkcommand_customvar
INFO[0001] Inserted 7 customvar_flats in 1.884699ms      action=insert benchmark=1.884699ms count=7 type=customvar_flat
INFO[0001] Inserted 7 customvars in 5.818799ms           action=insert benchmark=5.818799ms count=7 type=customvar
INFO[0001] Inserted 1 hosts in 1.085627ms                action=insert benchmark=1.085627ms count=1 type=host
INFO[0001] Inserted 1 host_states in 975599.000000ns     action=insert benchmark=975599.000000ns count=1 type=host_state
^CINFO[0011] Shutting down                                 signal=interrupt
➜  icingadb git:(feature/icingadb-scheduleddowntime-231) mysql -uicingadb -picingadb icingadb <<<'select name, creator from downtime;'
name	creator
Alexanders-MacBook-Pro.local!d	user
Alexanders-MacBook-Pro.local!785a4995-7edb-4f7e-8c40-581e68a856cd	scheduled_downtime
➜  icingadb git:(feature/icingadb-scheduleddowntime-231)
```

**Comment by julianbrost** [comment]
Will be closed by #257 anyways, no point in keeping this open.

**Comment by Al2Klimov** [comment]
#257 will be closed by #257?

**Pull request closed without merging**
