### PR TITLE
Adjust installation docs for centralized icinga.com doc injection

### PR DESCRIPTION
**Pull request by lippserd**
* Removes the package installation steps for the different operating systems to
have them injected centrally by our icinga.com documentation tools instead,
while maintaining readability and comprehensibility on GitHub and other
viewers.
* Adds `From Source` section to installation docs.

closes #818

### CODE REVIEW

**Review by oxzi — APPROVED** [review]
Looks good!

I have tested this PR with the example config just pushed over there: https://github.com/Icinga/icinga-docs-tools/pull/11

The output looked good and the right if-clause was used for the "From Source" install documentation.

**Review by yhabteab — APPROVED** [review]

**Comment by yhabteab** [comment]
Seems like something is wrong with Raspberry Pi OS includes:

While the Icinga DB Web images are included for all other distributions, including Debian, as follows `Icinga DB Web`, the includes for the `Raspberry Pi OS` installation are broken `Icinga DB Web`.

**Comment by yhabteab** [comment]
Actually, all the relative links are broken for Raspberry Pi.

**Comment by lippserd** [comment]
> Actually, all the relative links are broken for Raspberry Pi.

Fixed by Icinga/icinga-docs-tools#12.

**Pull request merged**
