### PR TITLE
Add more MySQL indexes

### PR DESCRIPTION
**Pull request by Yonas-net**
refs https://github.com/Icinga/icingadb-web/issues/404

### CODE REVIEW

**Comment by Yonas-net** [comment]
**Blocked by** https://github.com/Icinga/icinga2/issues/9049

**Comment by Yonas-net** [comment]
Test `history`, `downtime` and `service_state` indices whether they really improve the performance of Icinga DB Web.

**Comment by julianbrost** [comment]
What's the expected benefit for queries? Like is it more like unbearably slow -> acceptable or acceptable -> instant? Was write performance also considered when adding these?

**Comment by julianbrost** [comment]
I've done my standard schema upgrade diff from RC1 and it was fine. So if someone has a look that the actual changes are fine, this could be merged.

**Review by N-o-X — APPROVED** [review]

**Pull request merged**
